# Generated by Django 3.0.5 on 2020-04-23 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='barcode',
            field=models.CharField(blank=True, max_length=50, verbose_name='code-barre'),
        ),
        migrations.AddField(
            model_name='product',
            name='category_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category', to='search.Category', verbose_name='ID Catégorie'),
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.CharField(blank=True, max_length=200, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.URLField(blank=True, verbose_name='Photo'),
        ),
        migrations.AddField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='Nom'),
        ),
        migrations.AddField(
            model_name='product',
            name='nutriscore',
            field=models.CharField(blank=True, max_length=1, verbose_name='Nutriscore'),
        ),
        migrations.AddField(
            model_name='product',
            name='store',
            field=models.CharField(blank=True, max_length=200, verbose_name='Magasin(s)'),
        ),
        migrations.AddField(
            model_name='product',
            name='url',
            field=models.URLField(null=True, unique=True, verbose_name='URL'),
        ),
    ]
