# Generated by Django 3.0.5 on 2020-04-28 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0003_auto_20200423_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=200, null=True, unique=True, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='product',
            name='salt_for_100g',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True, verbose_name='Sel'),
        ),
        migrations.AlterField(
            model_name='product',
            name='saturated_fats_for_100g',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True, verbose_name='Acides gras'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sugars_for_100g',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True, verbose_name='Sucres'),
        ),
    ]
