# Generated by Django 3.0.5 on 2020-04-28 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0006_auto_20200428_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='lipids_for_100g',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True, verbose_name='Lipides'),
        ),
        migrations.AlterField(
            model_name='product',
            name='salt_for_100g',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True, verbose_name='Sel'),
        ),
        migrations.AlterField(
            model_name='product',
            name='saturated_fats_for_100g',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True, verbose_name='Acides gras'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sugars_for_100g',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True, verbose_name='Sucres'),
        ),
    ]
