# Generated by Django 3.0.5 on 2020-04-28 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0007_auto_20200428_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(blank=True, max_length=300, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=300, null=True, unique=True, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='product',
            name='store',
            field=models.CharField(blank=True, max_length=300, verbose_name='Magasin(s)'),
        ),
    ]
