# Generated by Django 3.0.5 on 2020-05-01 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0009_auto_20200428_1154'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
    ]
